USE [master]
GO

/****** Object:  Database [{{NAME}}_{{ENV}}]    Script Date: 07/27/2012 15:51:58 ******/
CREATE DATABASE [{{NAME}}_{{ENV}}] ON  PRIMARY 
( NAME = N'{{NAME}}_{{ENV}}', FILENAME = N'E:\MSSQL\MSSQL10.MSSQLSERVER\MSSQL\DATA\{{NAME}}_Corp_Dev.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'{{NAME}}_{{ENV}}_log', FILENAME = N'E:\MSSQL\MSSQL10.MSSQLSERVER\MSSQL\DATA\{{NAME}}_Corp_Dev_log.ldf' , SIZE = 29696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [{{NAME}}_{{ENV}}].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET ARITHABORT OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET  READ_WRITE 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [{{NAME}}_{{ENV}}] SET  MULTI_USER 
GO

if ( ((@@microsoftversion / power(2, 24) = 8) and (@@microsoftversion & 0xffff >= 760)) or 
		(@@microsoftversion / power(2, 24) >= 9) )begin 
	exec dbo.sp_dboption @dbname =  N'{{NAME}}_{{ENV}}', @optname = 'db chaining', @optvalue = 'OFF'
 end
GO

USE [{{NAME}}_{{ENV}}]
GO

